- hosts: web
  tasks:
  - name: "copy website"
    copy:
      src: site/
      dest: /var/www/default
  - name: "Replace"
    replace:
      path: /var/www/default/index.html
      regexp: '-change-'
      replace: '{{ ansible_port }}'
      backup: yes